export const phrases = [
  "Treasure map",
  "Broken heart",
  "Skipping rope",
  "Bursting bubbles",
  "Cat nap",
  "Midnight snack",
  "Bird's nest",
  "Floating feather",
  "Dancing shoes",
  "Lost keys",
  "Blowing candles",
  "Chasing dreams",
  "Pillow fight",
  "Roller coaster",
  "Hide and seek",
  "Laughing out loud",
  "Falling leaves",
  "Melting ice cream",
  "Sleeping bag",
  "Jumping jack",
  "Building sandcastles",
  "Climbing mountains",
  "Flying a kite",
  "Ringing bells",
  "Tying shoelaces",
  "Counting sheep",
  "Baking a cake",
  "Walking the dog",
  "Dripping faucet",
  "Window shopping",
  "Singing in the rain",
  "Spinning top",
  "Flying birds",
  "Brushing teeth",
  "Dancing in circles",
  "Planting a tree",
  "Reading a book",
  "Daydreaming",
  "Playing marbles",
  "Hopping on one foot",
  "Shooting stars",
  "Mowing the lawn",
  "Blowing a kiss",
  "Making lemonade",
  "Jumping in puddles",
  "Cooking breakfast",
  "Riding a scooter",
  "Peeling an orange",
  "Building a snowman",
  "Catching fireflies",
  "Sailing a boat",
  "Running a marathon",
  "Wearing sunglasses",
  "Drawing a picture",
  "Popping popcorn",
  "Telling secrets",
  "Folding laundry",
  "Hugging a teddy bear",
  "Raking leaves",
  "Making a wish",
  "Playing catch",
  "Chasing butterflies",
  "Swimming underwater",
  "Hanging ornaments",
  "Watching clouds",
  "Laying on a hammock",
  "Bouncing a basketball",
  "Climbing a ladder",
  "Flying a paper plane",
  "Roasting marshmallows",
  "Waving goodbye",
  "Hitting a pinata",
  "Playing the guitar",
  "Pushing a swing",
  "Eating spaghetti",
  "Magnifying glass",
  "Jigsaw puzzle",
  "Starry night",
]

const oneWord = [
  "Sunrise",
  "Picnic",
  "Fishing",
  "Shadow",
  "Rainbow",
  "Beehive",
  "Campfire",
  "Moonwalk",
  "Footprints",
  "Windmill",
  "Snowflake",
  "Guitar",
  "Balloon",
  "Candle",
  "Feather",
  "Magnet",
  "Ladder",
  "Piano",
  "Globe",
  "Anchor",
  "Hammer",
  "Teapot",
  "Kettle",
  "Mirror",
  "Bicycle",
  "Spoon",
  "Chalk",
  "Lantern",
  "Envelope",
  "Pillow",
  "Pyramid",
  "Penguin",
  "Volcano",
  "Butterfly",
  "Pumpkin",
  "Umbrella",
  "Sandal",
  "Tunnel",
  "Yarn",
  "Zebra",
  "Whale",
  "Vase",
  "Unicorn",
  "Trophy",
  "Scarf",
  "Ribbon",
  "Quill",
  "Paddle",
  "Ostrich"
]

const idioms = [
  "Bite the bullet",
  "Break a leg",
  "Cat got your tongue",
  "Dont cry over spilled milk",
  "Every cloud has a silver lining",
  "Hit the nail on the head",
  "Kick the bucket",
  "Let the cat out of the bag",
  "Once in a blue moon",
  "Put all your eggs in one basket",
  "Read between the lines",
  "Steal someone's thunder",
  "The ball is in your court",
  "Throw in the towel",
  "Under the weather",
  "When pigs fly",
  "A penny for your thoughts",
  "Burning the midnight oil",
  "Cry over spilled milk",
  "Dont put all your eggs in one basket",
  "Eyes bigger than your stomach",
  "Feeling under the weather",
  "Hitting the books",
  "In a pickle",
  "Jumping on the bandwagon",
  "Kill two birds with one stone",
  "Let sleeping dogs lie",
  "Missing the boat",
  "Not a cloud in the sky",
  "On cloud nine"
]

export const wordbank = [...oneWord, ...idioms, ...phrases].map(phrases => phrases.toLowerCase())